In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
import statsmodels.api as sm
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (14, 6)

In [23]:
from read_functions import dict_func

# Собираем мастер-фрейм
all_series = []
for path, func in dict_func.items():
    try:
        df = func(path)
        df['date'] = pd.to_datetime(df['date'])
        all_series.append(df.set_index('date'))
    except Exception as e:
        print(f"Ошибка загрузки {path}: {e}")

df_raw = pd.concat(all_series, axis=1)
df_raw = df_raw.sort_index()

print(f"Сырые данные загружены. Диапазон: с {df_raw.index.min().date()} по {df_raw.index.max().date()}")
print(f"Размерность: {df_raw.shape}")
df_raw.head()

Сырые данные загружены. Диапазон: с 1987-05-20 по 2026-03-02
Размерность: (5680, 70)

,loans_kz_total,loans_kz_biz_total,loans_kz_biz_kzt,loans_kz_biz_foreign,loans_kz_biz_small,loans_kz_biz_medium,loans_kz_biz_large,loans_kz_ind_total,loans_kz_ind_kzt,loans_kz_ind_foreign,loans_kz_ind_mortgage,loans_kz_ind_consumer,loans_kz_ind_others,cpi_kz_eoy_alcohol_tobacco,cpi_kz_eoy_soft_drinks,cpi_kz_eoy_housing_utilities,cpi_kz_eoy_health,cpi_kz_eoy_non_food_total,cpi_kz_eoy_education,cpi_kz_eoy_clothing_footwear,cpi_kz_eoy_recreation,cpi_kz_eoy_services_total,cpi_kz_eoy_household_items,cpi_kz_eoy_food_total,cpi_kz_eoy_food_only,cpi_kz_eoy_miscellaneous,cpi_kz_eoy_hotels_restaurants,cpi_kz_eoy_communication,cpi_kz_eoy_all,cpi_kz_eoy_transport,bond_kz_govt_cp_short_u1y,bond_kz_govt_cp_mid_1-5y,bond_kz_govt_cp_long_o5y,bond_kz_govt_cp_total,KASE_BMC,macro_kz_gdp_per_capita_usd,macro_kz_gdp_per_capita_kzt,macro_kz_gdp_per_capita_real_growth_pct,macro_kz_usd_kzt_avg,macro_kz_base_rate,macro_ru_key_rate,macro_ru_inflation_yoy,macro_ru_cpi_all_yoy,macro_ru_cpi_food_yoy,macro_ru_cpi_food_excl_alc_yoy,macro_ru_cpi_nonfood_yoy,macro_ru_cpi_services_yoy,bond_ru_ofz_yield_3m,bond_ru_ofz_yield_6m,bond_ru_ofz_yield_9m,bond_ru_ofz_yield_1y,bond_ru_ofz_yield_2y,bond_ru_ofz_yield_3y,bond_ru_ofz_yield_5y,bond_ru_ofz_yield_7y,bond_ru_ofz_yield_10y,bond_ru_ofz_yield_15y,bond_ru_ofz_yield_20y,macro_ru_labor_force,macro_ru_labor_employed,macro_ru_labor_unemployed,macro_ru_labor_participation_rate,macro_ru_labor_employment_rate,macro_ru_labor_unemployment_rate,macro_ru_ruonia_rate,macro_ru_ruonia_vol,bond_ru_corp_price_close,bond_ru_corp_yield,bond_ru_corp_duration,brent_price
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1987-05-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.63
1987-05-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.45
1987-05-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.55
1987-05-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.60
1987-05-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.63

In [24]:
# Ищем точку отсчета по сырым данным 
first_loan_date = df_raw['loans_kz_total'].dropna().index.min()
print(f"Старт выборки: {first_loan_date.date()}")

# Создаем  ежедневный календарь
daily_index = pd.date_range(start='2020-01-01', end='2026-01-01', freq='D')
df_processed = pd.DataFrame(index=daily_index).join(df_raw)

# Логарифмируем кредиты
loan_cols = [c for c in df_processed.columns if 'loans_kz' in c]
for col in loan_cols:
    df_processed[col] = np.log1p(df_processed[col])

# Разделяем признаки по логике заполнения
step_cols = ['macro_kz_base_rate', 'macro_ru_key_rate']
daily_market_cols = [
    c for c in df_processed.columns 
    if c.startswith('bond_') or c.startswith('brent') or c == 'KASE_BMC' or c.startswith('macro_ru_ruonia')
]
macro_interp_cols = [
    c for c in df_processed.columns 
    if c not in step_cols + daily_market_cols
]

df_processed[step_cols + daily_market_cols] = df_processed[step_cols + daily_market_cols].ffill()
df_processed[macro_interp_cols] = df_processed[macro_interp_cols].interpolate(method='linear')

df_processed = df_processed.ffill().bfill()

print(f"Размерность идеальной матрицы уровней: {df_processed.shape}")
df_processed.isna().sum().sum()

Старт выборки: 2022-01-01
Размерность идеальной матрицы уровней: (2193, 70)

0

In [25]:
def adf_test(series, signif=0.05):
    series_clean = series.dropna()
    if len(series_clean) < 30: return None, False
    try:
        res = adfuller(series_clean, autolag='AIC')
        return res[1], res[1] < signif
    except Exception:
        return None, False

df_stationary = pd.DataFrame(index=df_processed.index)
report = []

for col in df_processed.columns:
    raw_series = df_processed[col]
    
    # Тест Уровней
    p_val_0, is_stat_0 = adf_test(raw_series)
    
    if is_stat_0:
        df_stationary[col] = raw_series
        report.append({'Метрика': col, 'Порядок': 'I(0)', 'Действие': 'Без изменений', 'p-value': round(p_val_0, 4)})
    else:
        # Тест Первой разности
        diff1 = raw_series.diff()
        p_val_1, is_stat_1 = adf_test(diff1)
        
        if is_stat_1:
            df_stationary[col] = diff1
            report.append({'Метрика': col, 'Порядок': 'I(1)', 'Действие': '1-я разность', 'p-value': round(p_val_1, 4)})
        else:
            # Вторая разность
            diff2 = diff1.diff()
            df_stationary[col] = diff2
            report.append({'Метрика': col, 'Порядок': 'I(2)+', 'Действие': '2-я разность', 'p-value': '...'})

report_df = pd.DataFrame(report)
print("\n=== Отчет о стационарности ===")
with pd.option_context('display.max_rows', None):
    display(report_df)

# Из-за .diff() первая строчка (или две) станут NaN. Дропаем только их.
df_stationary_clean = df_stationary.dropna(how='all').dropna()
df_stationary_clean.to_csv('master_df_daily_stationary.csv')
print(f"\nСтационарная матрица готова и сохранена. Размерность: {df_stationary_clean.shape}")

=== Отчет о стационарности ===

                                    Метрика Порядок       Действие p-value
0                            loans_kz_total    I(1)   1-я разность     0.0
1                        loans_kz_biz_total    I(1)   1-я разность     0.0
2                          loans_kz_biz_kzt    I(1)   1-я разность     0.0
3                      loans_kz_biz_foreign    I(1)   1-я разность     0.0
4                        loans_kz_biz_small    I(1)   1-я разность     0.0
5                       loans_kz_biz_medium    I(1)   1-я разность     0.0
6                        loans_kz_biz_large    I(1)   1-я разность     0.0
7                        loans_kz_ind_total    I(1)   1-я разность  0.0473
8                          loans_kz_ind_kzt    I(1)   1-я разность  0.0484
9                      loans_kz_ind_foreign    I(1)   1-я разность     0.0
10                    loans_kz_ind_mortgage    I(1)   1-я разность  0.0147
11                    loans_kz_ind_consumer    I(1)   1-я разность  0.0043
12                      loans_kz_ind_others    I(1)   1-я разность     0.0
13               cpi_kz_eoy_alcohol_tobacco   I(2)+   2-я разность     ...
14                   cpi_kz_eoy_soft_drinks    I(0)  Без изменений  0.0227
15             cpi_kz_eoy_housing_utilities   I(2)+   2-я разность     ...
16                        cpi_kz_eoy_health   I(2)+   2-я разность     ...
17                cpi_kz_eoy_non_food_total    I(0)  Без изменений  0.0289
18                     cpi_kz_eoy_education    I(0)  Без изменений  0.0497
19             cpi_kz_eoy_clothing_footwear    I(0)  Без изменений  0.0424
20                    cpi_kz_eoy_recreation   I(2)+   2-я разность     ...
21                cpi_kz_eoy_services_total   I(2)+   2-я разность     ...
22               cpi_kz_eoy_household_items    I(0)  Без изменений  0.0477
23                    cpi_kz_eoy_food_total    I(0)  Без изменений  0.0336
24                     cpi_kz_eoy_food_only    I(0)  Без изменений  0.0353
25                 cpi_kz_eoy_miscellaneous    I(0)  Без изменений  0.0251
26            cpi_kz_eoy_hotels_restaurants    I(0)  Без изменений  0.0158
27                 cpi_kz_eoy_communication    I(0)  Без изменений  0.0369
28                           cpi_kz_eoy_all    I(0)  Без изменений  0.0248
29                     cpi_kz_eoy_transport    I(0)  Без изменений  0.0373
30                bond_kz_govt_cp_short_u1y    I(1)   1-я разность     0.0
31                 bond_kz_govt_cp_mid_1-5y    I(1)   1-я разность     0.0
32                 bond_kz_govt_cp_long_o5y    I(1)   1-я разность     0.0
33                    bond_kz_govt_cp_total    I(1)   1-я разность     0.0
34                                 KASE_BMC    I(1)   1-я разность     0.0
35              macro_kz_gdp_per_capita_usd   I(2)+   2-я разность     ...
36              macro_kz_gdp_per_capita_kzt   I(2)+   2-я разность     ...
37  macro_kz_gdp_per_capita_real_growth_pct   I(2)+   2-я разность     ...
38                     macro_kz_usd_kzt_avg   I(2)+   2-я разность     ...
39                       macro_kz_base_rate    I(1)   1-я разность     0.0
40                        macro_ru_key_rate    I(1)   1-я разность     0.0
41                   macro_ru_inflation_yoy    I(1)   1-я разность     0.0
42                     macro_ru_cpi_all_yoy    I(0)  Без изменений  0.0315
43                    macro_ru_cpi_food_yoy    I(0)  Без изменений  0.0207
44           macro_ru_cpi_food_excl_alc_yoy    I(0)  Без изменений  0.0215
45                 macro_ru_cpi_nonfood_yoy    I(0)  Без изменений  0.0476
46                macro_ru_cpi_services_yoy   I(2)+   2-я разность     ...
47                     bond_ru_ofz_yield_3m    I(1)   1-я разность     0.0
48                     bond_ru_ofz_yield_6m    I(1)   1-я разность     0.0
49                     bond_ru_ofz_yield_9m    I(1)   1-я разность     0.0
50                     bond_ru_ofz_yield_1y    I(1)   1-я разность     0.0
51                     bond_ru_ofz_yield_2y    I(1)   1-я разность     0.0
52                     bond_ru_ofz_yield_3y    I(1)   1-я разность     0.0
53                     bond_ru_ofz_yield_5y    I(1)   1-я разность     0.0
54                     bond_ru_ofz_yield_7y    I(1)   1-я разность     0.0
55                    bond_ru_ofz_yield_10y    I(1)   1-я разность     0.0
56                    bond_ru_ofz_yield_15y    I(1)   1-я разность     0.0
57                    bond_ru_ofz_yield_20y    I(1)   1-я разность     0.0
58                     macro_ru_labor_force    I(0)  Без изменений  0.0003
59                  macro_ru_labor_employed    I(1)   1-я разность     0.0
60                macro_ru_labor_unemployed    I(1)   1-я разность  0.0001
61        macro_ru_labor_participation_rate    I(0)  Без изменений  0.0309
62           macro_ru_labor_employment_rate    I(1)   1-я разность     0.0
63         macro_ru_labor_unemployment_rate    I(1)   1-я разность  0.0001
64                     macro_ru_ruonia_rate    I(1)   1-я разность     0.0
65                      macro_ru_ruonia_vol    I(1)   1-я разность     0.0
66                 bond_ru_corp_price_close    I(1)   1-я разность     0.0
67                       bond_ru_corp_yield    I(1)   1-я разность     0.0
68                    bond_ru_corp_duration    I(1)   1-я разность     0.0
69                              brent_price    I(1)   1-я разность     0.0

Стационарная матрица готова и сохранена. Размерность: (2191, 70)

In [42]:
df_raw_filtered = df_raw.loc['2020-01-01':'2026-01-01']

df_monthly_raw = df_raw_filtered.resample('ME').mean()

step_cols = ['macro_kz_base_rate', 'macro_ru_key_rate']
daily_market_cols = [
    c for c in df_monthly_raw.columns 
    if c.startswith('bond_') or c.startswith('brent') or c == 'KASE_BMC' or c.startswith('macro_ru_ruonia')
]
macro_interp_cols = [
    c for c in df_monthly_raw.columns 
    if c not in step_cols + daily_market_cols
]

df_monthly_raw[step_cols + daily_market_cols] = df_monthly_raw[step_cols + daily_market_cols].ffill()
df_monthly_raw[macro_interp_cols] = df_monthly_raw[macro_interp_cols].interpolate(method='linear')

df_monthly_processed = df_monthly_raw.ffill().bfill()

df_monthly_stationary = pd.DataFrame(index=df_monthly_processed.index)
monthly_report = []

for col in df_monthly_processed.columns:
    if 'loans_kz' in col:
        raw_series = np.log1p(df_monthly_processed[col])
    else:
        raw_series = df_monthly_processed[col]
        
    # Тест Уровней 
    p_val_0, is_stat_0 = adf_test(raw_series)
    
    if is_stat_0:
        df_monthly_stationary[col] = raw_series
        monthly_report.append({'Метрика': col, 'Порядок': 'I(0)', 'Действие': 'Без изменений', 'p-value': round(p_val_0, 4)})
    else:
        # Тест Первой разности
        diff1 = raw_series.diff()
        p_val_1, is_stat_1 = adf_test(diff1)
        
        if is_stat_1:
            df_monthly_stationary[col] = diff1
            monthly_report.append({'Метрика': col, 'Порядок': 'I(1)', 'Действие': '1-я разность', 'p-value': round(p_val_1, 4)})
        else:
            # Вторая разность
            diff2 = diff1.diff()
            df_monthly_stationary[col] = diff2
            monthly_report.append({'Метрика': col, 'Порядок': 'I(2)+', 'Действие': '2-я разность', 'p-value': '...'})

monthly_report_df = pd.DataFrame(monthly_report)

print("=== Отчет о стационарности (МЕСЯЧНАЯ гранулярность, корректный пайплайн) ===")
with pd.option_context('display.max_rows', None):
    display(monthly_report_df)

i2_metrics_monthly = monthly_report_df[monthly_report_df['Порядок'] == 'I(2)+']['Метрика'].tolist()
df_clean = df_monthly_stationary.drop(columns=[col for col in i2_metrics_monthly if col in df_monthly_stationary.columns]).dropna()

targets = [col for col in df_clean.columns if col.startswith('bond_ru_ofz_yield_')]
features = [col for col in df_clean.columns if col not in targets]

print(f"\nСтрок для обучения (МЕСЯЦЫ): {len(df_clean)}")
print(f"Таргетов (Y): {len(targets)}")
print(f"Признаков (X): {len(features)}")
print(f"Отброшено I(2)+ признаков: {len(i2_metrics_monthly)}\n")

=== Отчет о стационарности (МЕСЯЧНАЯ гранулярность, корректный пайплайн) ===

                                    Метрика Порядок       Действие p-value
0                            loans_kz_total   I(2)+   2-я разность     ...
1                        loans_kz_biz_total   I(2)+   2-я разность     ...
2                          loans_kz_biz_kzt   I(2)+   2-я разность     ...
3                      loans_kz_biz_foreign    I(1)   1-я разность     0.0
4                        loans_kz_biz_small    I(1)   1-я разность     0.0
5                       loans_kz_biz_medium    I(1)   1-я разность     0.0
6                        loans_kz_biz_large    I(1)   1-я разность     0.0
7                        loans_kz_ind_total    I(1)   1-я разность  0.0453
8                          loans_kz_ind_kzt    I(1)   1-я разность  0.0463
9                      loans_kz_ind_foreign    I(1)   1-я разность  0.0087
10                    loans_kz_ind_mortgage   I(2)+   2-я разность     ...
11                    loans_kz_ind_consumer   I(2)+   2-я разность     ...
12                      loans_kz_ind_others    I(1)   1-я разность     0.0
13               cpi_kz_eoy_alcohol_tobacco   I(2)+   2-я разность     ...
14                   cpi_kz_eoy_soft_drinks    I(0)  Без изменений  0.0198
15             cpi_kz_eoy_housing_utilities   I(2)+   2-я разность     ...
16                        cpi_kz_eoy_health   I(2)+   2-я разность     ...
17                cpi_kz_eoy_non_food_total    I(0)  Без изменений  0.0261
18                     cpi_kz_eoy_education    I(0)  Без изменений  0.0469
19             cpi_kz_eoy_clothing_footwear    I(0)  Без изменений  0.0392
20                    cpi_kz_eoy_recreation    I(0)  Без изменений     0.0
21                cpi_kz_eoy_services_total   I(2)+   2-я разность     ...
22               cpi_kz_eoy_household_items    I(0)  Без изменений  0.0479
23                    cpi_kz_eoy_food_total    I(0)  Без изменений  0.0321
24                     cpi_kz_eoy_food_only    I(0)  Без изменений  0.0341
25                 cpi_kz_eoy_miscellaneous    I(0)  Без изменений  0.0226
26            cpi_kz_eoy_hotels_restaurants    I(0)  Без изменений  0.0132
27                 cpi_kz_eoy_communication    I(0)  Без изменений  0.0365
28                           cpi_kz_eoy_all    I(0)  Без изменений   0.022
29                     cpi_kz_eoy_transport   I(2)+   2-я разность     ...
30                bond_kz_govt_cp_short_u1y   I(2)+   2-я разность     ...
31                 bond_kz_govt_cp_mid_1-5y    I(1)   1-я разность     0.0
32                 bond_kz_govt_cp_long_o5y    I(1)   1-я разность     0.0
33                    bond_kz_govt_cp_total    I(0)  Без изменений  0.0169
34                                 KASE_BMC   I(2)+   2-я разность     ...
35              macro_kz_gdp_per_capita_usd   I(2)+   2-я разность     ...
36              macro_kz_gdp_per_capita_kzt   I(2)+   2-я разность     ...
37  macro_kz_gdp_per_capita_real_growth_pct    I(0)  Без изменений  0.0297
38                     macro_kz_usd_kzt_avg    I(0)  Без изменений     0.0
39                       macro_kz_base_rate    I(1)   1-я разность     0.0
40                        macro_ru_key_rate    I(1)   1-я разность     0.0
41                   macro_ru_inflation_yoy    I(1)   1-я разность     0.0
42                     macro_ru_cpi_all_yoy    I(0)  Без изменений  0.0346
43                    macro_ru_cpi_food_yoy    I(0)  Без изменений  0.0227
44           macro_ru_cpi_food_excl_alc_yoy    I(0)  Без изменений  0.0235
45                 macro_ru_cpi_nonfood_yoy   I(2)+   2-я разность     ...
46                macro_ru_cpi_services_yoy   I(2)+   2-я разность     ...
47                     bond_ru_ofz_yield_3m    I(1)   1-я разность     0.0
48                     bond_ru_ofz_yield_6m    I(1)   1-я разность     0.0
49                     bond_ru_ofz_yield_9m    I(1)   1-я разность     0.0
50                     bond_ru_ofz_yield_1y    I(1)   1-я разность     0.0
51                     bond_ru_ofz_yield_2y    I(1)   1-я разность     0.0
52                     bond_ru_ofz_yield_3y    I(1)   1-я разность     0.0
53                     bond_ru_ofz_yield_5y    I(1)   1-я разность     0.0
54                     bond_ru_ofz_yield_7y    I(1)   1-я разность     0.0
55                    bond_ru_ofz_yield_10y    I(1)   1-я разность     0.0
56                    bond_ru_ofz_yield_15y    I(1)   1-я разность     0.0
57                    bond_ru_ofz_yield_20y    I(1)   1-я разность     0.0
58                     macro_ru_labor_force    I(0)  Без изменений  0.0141
59                  macro_ru_labor_employed    I(1)   1-я разность     0.0
60                macro_ru_labor_unemployed    I(1)   1-я разность  0.0013
61        macro_ru_labor_participation_rate    I(1)   1-я разность     0.0
62           macro_ru_labor_employment_rate    I(1)   1-я разность     0.0
63         macro_ru_labor_unemployment_rate    I(1)   1-я разность  0.0028
64                     macro_ru_ruonia_rate    I(1)   1-я разность     0.0
65                      macro_ru_ruonia_vol    I(1)   1-я разность     0.0
66                 bond_ru_corp_price_close    I(1)   1-я разность     0.0
67                       bond_ru_corp_yield    I(1)   1-я разность     0.0
68                    bond_ru_corp_duration   I(2)+   2-я разность     ...
69                              brent_price    I(1)   1-я разность     0.0

Строк для обучения (МЕСЯЦЫ): 72
Таргетов (Y): 11
Признаков (X): 42
Отброшено I(2)+ признаков: 17

In [43]:
results_ols = []

for target in targets:
    Y = df_clean[target]
    X = df_clean[features]
    X = sm.add_constant(X)
    
    try:
        model = sm.OLS(Y, X).fit()
        pvals = model.pvalues.drop('const')
        
        sig_features = pvals[pvals < 0.05].sort_values()
        top_factors_str = ", ".join([f"{feat} (p={pval:.3f})" for feat, pval in list(sig_features.items())[:4]])
        
        results_ols.append({
            'Срок до погашения': target,
            # 'R²': model.rsquared,
            'Adj. R²': model.rsquared_adj,
            'Топ значимых предикторов (OLS)': top_factors_str if top_factors_str else "Нет значимых факторов"
        })
    except Exception as e:
        results_ols.append({
            'Облигация (Таргет)': target,
            # 'R²': 0,
            'Adj. R²': 0,
            'Топ значимых предикторов (OLS)': f"Ошибка: {e}"
        })

res_ols_df = pd.DataFrame(results_ols).set_index('Срок до погашения')
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(res_ols_df.style.background_gradient(subset=['Adj. R²'], cmap='Blues', vmin=0, vmax=1).set_table_attributes('style="width: 70% !important; margin-right: auto;"'))